# Generated by Django 5.0.1 on 2024-02-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareModel',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post_offer_return', models.FloatField()),
            ],
        ),
    ]
