# Generated by Django 5.0.1 on 2024-02-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareModel',
        ),
    ]
